[package]
name = "disk_scrub"
version = "0.1.1-beta.10"
edition = "2021"

[dependencies]
tempfile = "3.3.0"
hex = "0.4.3"
sha2 = "0.10.2"
clap = { version = "3.2.15", features = ["derive"] }
wildmatch = "2.1.1"
