name: Beta Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Release build
      run: cargo build --release
    - name: copy artifacts
      run: |
        rm -rf downloads
        mkdir downloads
        cp target/release/disk_scrub downloads/
    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: assets-for-download
        path: downloads
